version: '3.9'
services:
 app:
  build:
    context: .
  container_name: node18-14-0/2
  tty: true
  volumes:
    - ./blog-app:/app
  environment:
    - WATCHPACK_POLLING=true
  ports:
    - "3000:3000"